name: Deploy swaps-keepers image to cloud registry

on:
    push:
        tags:
            - 'swaps-keepers/v*'

env:
    PROJECT_ID: ${{ secrets.KEEPERS_PROJECT_ID }}
    IMAGE: swaps-keepers

jobs:
    setup-and-deploy:
        name: Setup and Deploy
        runs-on: ubuntu-latest

        # Add "id-token" with the intended permissions.
        permissions:
            contents: "read"
            id-token: "write"

        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - uses: vmware-tanzu/carvel-setup-action@v1

            # Alternative option - authentication via credentials json
            - id: "auth"
              uses: "google-github-actions/auth@v0"
              with:
                  credentials_json: "${{ secrets.KEEPERS_SA_KEY }}"

            # Setup gcloud CLI
            - name: Set up Cloud SDK
              uses: google-github-actions/setup-gcloud@v0

            # Configure Docker to use the gcloud command-line tool as a credential
            # helper for authentication
            - run: |-
                  gcloud --quiet auth configure-docker

            - run: yarn install --frozen-lockfile
            - run: npm run build

            # Build the Docker image
            - name: Build
              run: |-
                  docker build \
                    -f "./packages/swaps-keepers/Dockerfile" \
                    --tag "gcr.io/$PROJECT_ID/$IMAGE:$GITHUB_SHA" \
                    --tag "latest" \
                    --build-arg GITHUB_SHA="$GITHUB_SHA" \
                    --build-arg GITHUB_REF="$GITHUB_REF" \
                    .

            # Push the Docker image to Google Container Registry
            - name: Publish
              run: |-
                  docker push "gcr.io/$PROJECT_ID/$IMAGE:$GITHUB_SHA"
